### ISSUE TITLE
Permission error to install tsd-s3cmd

### ISSUE THREAD

**Issue by zillurbmb51** [unioslo/tsd-s3cmd#3]
Hi,
I was trying to install  `tsd-s3cmd` in `nird.sigma2.no` `pip3 install https://github.com/unioslo/tsd-s3cmd/archive/v0.1.1.zip
`but getting permission error.
`PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.6'`

Any help?

**Comment by ofrei** [comment]
Hi Zillur
Try ``pip3 install --user https://github.com/unioslo/tsd-s3cmd/archive/v0.1.1.zip``

**Comment by zillurbmb51** [comment]
Thanks. It works.
